- hosts: localhost
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "public-compute-instance"
      key_name: "prod-ssh-key"
      vpc_subnet_id: subnet-86258ffe
      instance_type: t2.micro
      security_group: default
      state: running
      network:
        assign_public_ip: true
      image_id: ami-0892d3c7ee96c0bf7
      tags:
        Environment: Testing
    register: returned_stuff

  - name: Install redis
    remote_user: ubuntu
    become: true
    delegate_to: "{{ returned_stuff.instances[0].network_interfaces[0].association.public_ip }}"
    apt:
      name: redis
      state: latest
      update_cache: yes

  - name: "get nodejs"
    remote_user: ubuntu
    become: true
    delegate_to: "{{ returned_stuff.instances[0].network_interfaces[0].association.public_ip }}"
    ansible.builtin.shell: curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
  
  - name: "Install node"
    remote_user: ubuntu
    become: true
    delegate_to: "{{ returned_stuff.instances[0].network_interfaces[0].association.public_ip }}"
    ansible.builtin.shell: bash nodesource_setup.sh
  
  - name: "Update npm"
    remote_user: ubuntu
    become: true
    delegate_to: "{{ returned_stuff.instances[0].network_interfaces[0].association.public_ip }}"
    ansible.builtin.shell: apt install nodejs -y

  - name: "pm2 install"
    remote_user: ubuntu
    become: true
    delegate_to: "{{ returned_stuff.instances[0].network_interfaces[0].association.public_ip }}"
    ansible.builtin.shell: npm install pm2@latest -g